name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Operator PR
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GHA_TOKEN }}"
        with:
          name: "mariadb-operator"
          version: "v0.0.30"
          fork-repo-name: "mariadb-operator/certified-operators"
          upstream-repo-name: "redhat-openshift-ecosystem/certified-operators"
          bundle-path-dir: "deploy/olm"
          ci-path-file: "deploy/olm/ci.yaml"
          user-name: "Martin Montes"
          user-email: "martin11lrx@gmail.com"
          dry-run: true